spring.application.name=BlogApp

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres-service:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

security.secret.key=edc0c2ea99387d88f8bea095099ba9a90ac194796414375885c77d59ca850c68
security.secret.time=3600000

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=false
